---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kibana
spec:
  template:
    metadata:
      labels:
        application: logging
        component: kibana
    spec:
      containers:
      - name: kibana
        imagePullPolicy: IfNotPresent
        image: docker.elastic.co/kibana/kibana:5.6.3
        resources:
          requests:
            memory: 2Gi
            cpu: 1
          limits:
            memory: 2Gi
            cpu: 1
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVER_NAME
          value: "kibana.test.com"
        - name: ELASTICSEARCH_URL
          value: "http://es-ingest:9200"
        - name: XPACK_MONITORING_ENABLED
          value: "true"
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config/kibana.yml.new
          subPath: kibana.yml.new
      volumes:
      - name: config
        configMap:
          name: kibana-config
      restartPolicy: Always
