apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kibana
  labels:
    application: logging
    component: kibana
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: kibana
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
