---
apiVersion: v1
kind: Service
metadata:
  name: es-master
  labels:
    application: logging
    component: elasticsearch
    role: master
spec:
  ports:
  - port: 9300
    name: transport
  clusterIP: None
  selector:
    component: elasticsearch
    role: master
