---
apiVersion: v1
kind: Service
metadata:
  name: logstash-syslog-udp
  labels:
    application: logging
    component: logstash
spec:
  type: LoadBalancer
  ports:
  - port: 514
    targetPort: 514
    protocol: UDP
    name: logstash-syslog-udp
  selector:
    component: logstash
